--- 
assignees: 
  - DaRealTurtyWurty
body: 
  - 
    attributes: ~
    type: markdown
    value: "Thanks for taking the time to create this bug report and help us improve Railroad IDE!\n"
  - 
    attributes: 
      description: "What are the steps that we can use to reproduce the bug?"
      label: "Steps to reproduce."
      placeholder: "1. Open the IDE 2. Press Esc 3. etc..."
    id: what-happened
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Tell us what happened and what you expected to happen?"
      label: "What happened?"
      placeholder: "Tell us what you see!"
    id: what-happened
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "What branch(es) did this bug occur on?"
      label: Version
      multiple: true
      options: 
        - "main (Default)"
        - "docking (Docking & Layout)"
    id: version
    type: dropdown
    validations: 
      required: true
  - 
    attributes: 
      description: ~
      label: "What operating system(s) is this issue occuring on?"
      multiple: true
      options: 
        - Windows
        - MacOS
        - Linux
        - Other
    id: operating-system
    type: dropdown
    validations: 
      required: true
  - 
    attributes: 
      label: "If you selected 'Other' for the operating system(s), please specify."
    id: other-operating-system
    type: textarea
  - 
    attributes: 
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      label: "Relevant log output"
      render: log
    id: logs
    type: textarea
description: "File a bug report."
labels: 
  - bug
  - triage
name: "Bug Report"
